import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#0a0e18',
        'surface-container-low': '#171b26',
        'surface-container': '#1c1f2a',
        'surface-container-high': '#262a35',
        'surface-container-highest': '#313540',
        'surface': '#0f131d',
        'surface-dim': '#0f131d',
        'surface-bright': '#353944',
        'surface-variant': '#313540',
        'background': '#0f131d',
        'on-background': '#dfe2f1',
        'on-surface': '#dfe2f1',
        'on-surface-variant': '#ccc3d8',
        'primary': '#d2bbff',
        'primary-container': '#7c3aed',
        'on-primary': '#3f008e',
        'on-primary-container': '#ede0ff',
        'primary-fixed': '#eaddff',
        'primary-fixed-dim': '#d2bbff',
        'on-primary-fixed': '#25005a',
        'on-primary-fixed-variant': '#5a00c6',
        'inverse-primary': '#732ee4',
        'secondary': '#bdc7d9',
        'secondary-container': '#404a59',
        'on-secondary': '#27313f',
        'on-secondary-container': '#afb9cb',
        'secondary-fixed': '#d9e3f6',
        'secondary-fixed-dim': '#bdc7d9',
        'on-secondary-fixed': '#121c2a',
        'on-secondary-fixed-variant': '#3d4756',
        'tertiary': '#c0c6db',
        'tertiary-container': '#5f6678',
        'on-tertiary': '#293040',
        'on-tertiary-container': '#dfe5fa',
        'tertiary-fixed': '#dce2f7',
        'tertiary-fixed-dim': '#c0c6db',
        'on-tertiary-fixed': '#141b2b',
        'on-tertiary-fixed-variant': '#404758',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'outline': '#958da1',
        'outline-variant': '#4a4455',
        'inverse-surface': '#dfe2f1',
        'inverse-on-surface': '#2c303b',
        'surface-tint': '#d2bbff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'edge-margin': '1rem',
        'gutter': '1rem',
        'stack-sm': '0.5rem',
        'stack-md': '1rem',
        'stack-lg': '1.5rem',
        'container-max-width': '480px',
      },
      fontFamily: {
        'headline-xl': ['Space Grotesk'],
        'headline-lg': ['Space Grotesk'],
        'headline-md': ['Space Grotesk'],
        'headline-xl-mobile': ['Space Grotesk'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'label-md': ['Inter'],
      },
      fontSize: {
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '600' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
} satisfies Config
